# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: dellemc
name: sfm
version: 1.0.0
readme: README.md
authors:
  - Baskaran Jeyapaul (github.com/baskaran-jeyapaul)
description: null
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - dellemc
  - dell
  - networking
  - sfm
dependencies: 
  "ansible.netcommon": ">=2.0.0"
repository: https://github.com/ansible-collections/community.REPO_NAME
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/community.REPO_NAME
issues: https://github.com/ansible-collections/community.REPO_NAME/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
