#
# -*- coding: utf-8 -*-
# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the sfm_networks module
"""


class NetworksArgs(object):  # pylint: disable=R0903
    """The arg spec for the sfm_networks module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
            'options': {'address_family': {'choices': ['INET', 'INETV6'],
                                           'type': 'str'},
                        'gateway_ip_address': {'elements': 'dict',
                                               'options': {'name': {'type': 'str'}},
                                               'type': 'list'},
                        'ip_address_list': {'elements': 'dict',
                                            'options': {'name': {'type': 'str'}},
                                            'type': 'list'},
                        'network_id': {'type': 'str'},
                        'network_name': {'type': 'str'},
                        'network_type': {'choices': ['MultiRackVlan',
                                                     'Vlan',
                                                     'L3Routed',
                                                     'VxLan'],
                                         'type': 'str'},
                        'originator': {'type': 'str'},
                        'prefix_length': {'type': 'int'},
                        'qos_priority': {'choices': ['Iron',
                                                     'Bronze',
                                                     'Silver',
                                                     'Gold',
                                                     'Platinum',
                                                     'System'],
                                         'default': 'Silver',
                                         'type': 'str'},
                        'tenant_id': {'type': 'str'},
                        'vlan_max': {'type': 'int'},
                        'vlan_min': {'type': 'int'}},
            'type': 'list'},
 'state': {'choices': ['merged', 'deleted'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
