#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sfm_fabrics
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


DOCUMENTATION = """
---
module: sfm_fabrics
version_added: 1.0.0
short_description: Manages Fabrics attributes of sfm configuration
description: This Module Manages Fabrics attributes of sfm configuration
author: Baskaran Jeyapaul
notes:
  - Tested against sfm 1.0.0
options:
  config:
    description: List of sfm Fabrics attributes configuration
    type: list
    elements: dict
    suboptions:
      fabric_id:
        type: str
        description: Fabric Identifier
      name:
        type: str
        description: Fabric Name
      fabric_blue_print:
        type: str
        description: Fabric Blue Print
      fabric_type:
        type: str
        description:
        - Fabric Type
        choices:
        - None
        - VxLan
        - L3
        - L2
        default: VxLan
      super_spines:
        description: List of Super Spines Node Identifier
        type: list
        elements: dict
        suboptions:
          name:
            type: str
            description: Super Spines Node Identifier
      spines:
        description: List of Spines Node Identifier
        type: list
        elements: dict
        suboptions:
          name:
            type: str
            description: Spines Node Identifier
      leaves:
        description: List of Leaves Node Identifier
        type: list
        elements: dict
        suboptions:
          name:
            type: str
            description: Leaves Node Identifier
      vlt_links:
        description:
          - List of source and destination vlt links
        type: list
        elements: dict
        suboptions:
          source:
            description:
              - Source Vlt interface name with node id
            type: str
          destination:
            description:
              - Destination Vlt interface name with node id
            type: str

  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - deleted
    default: merged
"""
EXAMPLES = """
# Using deleted

# configuration example prior to module invocation

- name: Delete sfm Fabrics attributes
  dellemc.sfm.sfm_fabrics:
    config:
    state: deleted

# configuration example after module invocation


# Using merged

# configuration example prior to module invocation

#- name: Configure sfm Fabrics attributes

# configuration example after module invocation


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.sfm.plugins.module_utils.network.sfm.argspec.fabrics.fabrics import FabricsArgs
from ansible_collections.dellemc.sfm.plugins.module_utils.network.sfm.config.fabrics.fabrics import Fabrics


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=FabricsArgs.argument_spec,
                           supports_check_mode=True)

    result = Fabrics(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
