#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sfm_nodes
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = """
---
module: sfm_nodes
version_added: 1.0.0
short_description: Manages Nodes attributes of sfm configuration
description: This Module Manages Nodes attributes of sfm configuration
author: Baskaran Jeyapaul
notes:
  - Tested against sfm 1.0.0
options:
  config:
    description: List of sfm Nodes attributes configuration
    type: list
    elements: dict
    suboptions:
      node_id:
        type: str
        description: Node Identifier
      node_type:
        type: str
        description:
        - Node Type
        choices:
        - DellSonic
        default: DellSonic
      node_config_type:
        type: str
        description:
        - Node Config Type
        choices:
        - OpenConfig
        default: OpenConfig
      ip_address:
        type: str
        description: IP Address
      user_name:
        type: str
        description: User Name
      password:
        type: str
        description: Password
      port:
        description:
        - Port value.
        type: int
      node_role:
        type: str
        description:
        - Node Role
        choices:
        - FullSwitch
        - Leaf
        - Spine
        - SuperSpine
      node_name:
        type: str
        description: Node Name
  state:
    description:
    - The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - deleted
    default: merged
"""
EXAMPLES = """
# Using deleted

# configuration example prior to module invocation

- name: Delete sfm Nodes attributes
  dellemc.sfm.sfm_nodes:
    config:
    state: deleted

# configuration example after module invocation


# Using merged

# configuration example prior to module invocation

#- name: Configure sfm Nodes attributes

# configuration example after module invocation


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.sfm.plugins.module_utils.network.sfm.argspec.nodes.nodes import NodesArgs
from ansible_collections.dellemc.sfm.plugins.module_utils.network.sfm.config.nodes.nodes import Nodes


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=NodesArgs.argument_spec,
                           supports_check_mode=True)

    result = Nodes(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
